apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-daemonset
  namespace: default
  finalizers:
    - image-cloner/del-protection
spec:
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-container
          image: alpine
          command: ["sh", "-c", "while true; do sleep 3600; done"]