apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-cloner-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: image-cloner-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: image-cloner-role
  apiGroup: rbac.authorization.k8s.io
