apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-cloner-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["deployments/finalizers", "daemonsets/finalizers"]
    verbs: ["get", "list", "update"]